version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "3000:3000"
    hostname: backend
    environment:
      - NODE_ENV=development
    user: "node"
    command: npm run dev
    volumes:
      - ./backend/certs:/home/node/app/src/certs
      - ./.env:/home/node/app/.env
    networks:
      - transcendent-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    user: "node"
    depends_on:
      - backend
    command: npm run dev -- --host
    networks:
      - transcendent-net

volumes:
  db-data:
    driver: local

networks:
  transcendent-net:
    driver: bridge