FROM node:20-alpine

USER node
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]