FROM node:20-alpine

RUN apk add --no-cache sqlite

USER node
WORKDIR /home/node/app

RUN mkdir -p data

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]